info:
  description: "Service for Product Test Service"

spring:
  application:
    name: product-test-service

security:
  basic:
    enabled: false

server:
  port: 9093

common:
  web:
    config:
      swagger:
        controllerPackage: com.oauthex.productservice.controller
        author: Panneerselvam
        apiName: Product Service API
        apiVersion: v1
        apiDescription: Product-service
        enabled: true